### ISSUE TITLE
Keep showing properties with no key frames

### ISSUE THREAD

**Issue by thorikawa** [idflood/TweenTime#44]
I would like to keep showing properties with no key frames, so the user can add key frames to the property which does not have key frames at the beginning. This change is already in my branch, but I opened this issue to hear the opinion, because this change would affect the existing project using this library.

https://github.com/thorikawa/TweenTime/commit/baea2b27b9874bd000e7e354a6b9484dc6fa59b4

@idflood Any opinion?

**Comment by idflood** [comment]
Could we make this optional like:

    var editor = new TweenTime.Editor(tweenTime, {showEmptyProperties: true});

What do you think?

**Comment by thorikawa** [comment]
That sounds good to me. I will make PR for it.
